"""empty message

Revision ID: 2700f7d183ba
Revises: f3d4c0155754
Create Date: 2020-05-04 23:21:30.728942

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2700f7d183ba'
down_revision = 'f3d4c0155754'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Actor', sa.Column('movies', sa.ARRAY(sa.String()), nullable=True))
    op.alter_column('Actor', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.add_column('Movie', sa.Column('actors', sa.ARRAY(sa.String()), nullable=True))
    op.alter_column('Movie', 'title',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Movie', 'title',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('Movie', 'actors')
    op.alter_column('Actor', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('Actor', 'movies')
    # ### end Alembic commands ###
